---
# tasks file for dns
- name: Upgrade package
  package:
    name: "*"
    state: latest

- name: Install DNS package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ dns_packages }}"

- name: Configure DNS master file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'templates/named.conf.j2', dest: '/etc/named.conf', owner: 'root', group: 'named', mode: '644' }
    - { src: 'templates/named.rfc1912.zones.j2', dest: '/etc/named.rfc1912.zones', owner: 'root', group: 'named', mode: '644' }
    - { src: 'templates/f.zone.j2', dest: '/var/named/f.zone', owner: 'root', group: 'named', mode: '644' }
    - { src: 'templates/r.zone.j2', dest: '/var/named/r.zone', owner: 'root', group: 'named', mode: '644' }
  notify:
    - restart dns
   

